### ISSUE TITLE
Critique - Round #1

### ISSUE THREAD

**Issue by teward** [benqzq/uncwe#4]
> Critique was requested in Ask Ubuntu General Room on StackExchange by [user9303970](https://unix.stackexchange.com/users/273994/user9303970)

- Installing CertBot - why?  You don't use it in your software or script.  Nor do you use it in the site configuration with nginx or otherwise, which will introduce issues.
- **_INSECURE_** - Using `source` to pull things in will break things.  Why are you not just executing individual scripts within a master one, and fix the `^M` problem yourself *first*?

**It also doesn't work out of the box.**  You don't specify how a user should *access* the Wordpress installation, so users may assume that the root of the server will "just work" with Wordpress.  Instead they get a default page.  And it doesn't actually set up any wordpress sites to the point where you can actually *install* them.  This should be doing most of those steps out of the box if you expect this to be a good 'environment' setup utility.

You also don't properly execute commands, and do this:

```
while read file; do source ~/unwe/"$file"
done <<-EOF
    assignments.sh
    php_conf.sh
    phpmyadmin.sh
    wp-cli.sh
    crontab.sh
EOF
```

But this is insecure, and you *should* be instead executing the scripts directly...

```
assignments.sh
php_conf.sh
phpmyadmin.sh
wp-cli.sh
crontab.sh
```

... which you don't do.

From a security perspective this is a "no go" and should not be used for anything.  It is better to set everything up by hand than use your insecure (and honestly, non-working) project to set up a Wordpress on NGINX environment.

**Comment by benqzq** [comment]
Thomas, I took care of all of this:
1. I changed the name of the project and changed the README (expanded accordingly) on the fact this project is aimed for external sites with HTTPS.
2. I deleted all direct `source` commands (I only print a 2 source commands into `/etc/bash.bashrc`, see `install_localize.sh`).
3. I removed the `while`-`heredocument` you described as insecure; Instead, I now `bash` the commands directly (see `install_localize.sh`), as you shown.
4. I also grouped nearly all project files into contexts, by their file name (please see file list in project).
5. I further splitted project files.
6. I went fully modular (please see `install.sh`).

I've yet to test the script (will do so very soon), but I really doubt it would seem problematic to you now, but please tell me if anything seems problematic.

**Comment by benqzq** [comment]
All issues mentioned here were fixed. Certbot is an intergral part of this project.
